const countryCodeMapping = {
  Argentine: "AR",
  American: "US",
  Australian: "AU",
  Austrian: "AT",
  Azerbaijani: "AZ",
  Bahrain: "BH",
  Belgian: "BE",
  Brazilian: "BR",
  British: "GB",
  Canadian: "CA",
  Chilean: "CL",
  Chinese: "CN",
  Colombian: "CO",
  Danish: "DK",
  Dutch: "NL",
  Finnish: "FI",
  French: "FR",
  German: "DE",
  Hungarian: "HU",
  Indian: "IN",
  Indonesian: "ID",
  Irish: "IE",
  Italian: "IT",
  Japanese: "JP",
  Liechtensteiner: "LI",
  Malaysian: "MY",
  Mexican: "MX",
  Monegasque: "MC",
  "New Zealander": "NZ",
  Norwegian: "NO",
  Polish: "PL",
  Portuguese: "PT",
  Qatari: "QA",
  Russian: "RU",
  Saudi: "SA",
  Singaporean: "SG",
  "South African": "ZA",
  Spanish: "ES",
  Swedish: "SE",
  Swiss: "CH",
  Thai: "TH",
  Turkish: "TR",
  Uruguayan: "UY",
  Venezuelan: "VE",
  Austria: "AT",
  Australia: "AU",
  Azerbaijan: "AZ",
  Belgium: "BE",
  Brazil: "BR",
  Canada: "CA",
  China: "CN",
  Colombia: "CO",
  Czech: "CZ",
  Denmark: "DK",
  Finland: "FI",
  France: "FR",
  Germany: "DE",
  Hungary: "HU",
  India: "IN",
  Indonesia: "ID",
  Ireland: "IE",
  Italy: "IT",
  Japan: "JP",
  Liechtenstein: "LI",
  Malaysia: "MY",
  Mexico: "MX",
  Monaco: "MC",
  Netherlands: "NL",
  "New Zealand": "NZ",
  Norway: "NO",
  Poland: "PL",
  Portugal: "PT",
  Qatar: "QA",
  Russia: "RU",
  "Saudi Arabia": "SA",
  Singapore: "SG",
  "South Africa": "ZA",
  Spain: "ES",
  Sweden: "SE",
  Switzerland: "CH",
  Thailand: "TH",
  Turkey: "TR",
  Uruguay: "UY",
  UK: "GB",
  USA: "US",
  "United States": "US",
  UAE: "AE",
  Venezuela: "VE",
};

export default countryCodeMapping;
